development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= Figaro.env.REDIS_URL { "redis://localhost:6379/1" } %>
  channel_prefix: rails_api_boilerplate_production
